# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
          FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
          ROLE_ADMIN:       ROLE_USER
          ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
      fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            anonymous:    true
            logout:
                path: fos_user_security_logout
                target: /login

    access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/, role: ROLE_ADMIN }
          - { path: ^/todos/delete, role: ROLE_USER }
          - { path: ^/todos/edit, role: ROLE_USER }
          - { path: ^/, role: ROLE_USER }
